# -*- coding: utf-8 -*-
"""oop_library_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKVZ7nnfdxYPFDEkZSzwQrZRypBu3uHl
"""

# Smart Library Management System (OOP Project)
class Book:
    def __init__(self, id, title, author):
        self.id = id
        self.title = title
        self.author = author
        self.available = True

class Student:
    def __init__(self, name):
        self.name = name

    def borrow_book(self, book):
        if book.available:
            book.available = False
            print("Book borrowed")
        else:
            print("Book not available")

class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)

    def show_books(self):
        for book in self.books:
            print(book.title)


lib = Library()

book1 = Book(1, "Python Basics", "Guido")
book2 = Book(2, "AI Fundamentals", "Russell")

lib.add_book(book1)
lib.add_book(book2)

print("Available Books:")
lib.show_books()

s1 = Student("Himani")

s1.borrow_book(book1)

s1.borrow_book(book1)